name: Release Obsidian Plugin

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9+]'
      - 'v[0-9]+.[0-9]+.[0-9+]'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Verify build artifacts
        run: |
          test -f main.js || (echo 'main.js missing' && exit 1)
          test -f manifest.json || (echo 'manifest.json missing' && exit 1)
          if [ -f styles.css ]; then echo 'styles.css present (optional)'; else echo 'styles.css missing (ok if unused)'; fi

      - name: Derive version
        id: ver
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          # Strip leading v for release name and asset tag
          CLEAN_TAG="${TAG#v}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "clean_tag=${CLEAN_TAG}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.ver.outputs.tag }}
          name: ${{ steps.ver.outputs.clean_tag }}
          draft: false
          prerelease: false
          files: |
            manifest.json
            main.js
            styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
